name: Flatpak

on: [push, pull_request]

jobs:

  flatpak:
    runs-on: ubuntu-20.04
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-3.38
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: com.github.amikha1lov.RecAppDevel.flatpak
        manifest-path: com.github.amikha1lov.RecApp.yaml
        run-tests: true
